### ISSUE TITLE
Word Wrap

### ISSUE THREAD

**Issue by kerim** [mikaelbr/markdowner#4]
It would be good to be able to toggle word-wrap so that longer blocks of text don't require horizontal scroll. Especially useful for those using markdown for purposes other than writing code.

**Comment by mikaelbr** [comment]
The initial thought was to have the editor as simple as possible, but I can see the point of having some options/preferences. I'll label this as an enhancement and I'll get around to it.

**Comment by kerim** [comment]
Thanks!
