### ISSUE TITLE
Publish?

### ISSUE THREAD

**Issue by kerim** [mikaelbr/markdowner#5]
This is more of a question than a request. I'm curious what your plans are for this with regard to publishing file contents. As far as I can tell right now, it isn't possible to publish a Remark slideshow so that it is world-visible?

**Comment by mikaelbr** [comment]
As per now, a slideshow must be pulic, yes. This was a side effect of how the preview-frame was developed. But I could easily change this, and that would probably make most sense. 

I'll lable this as a Bug, and fix it when I get the time.

**Comment by kerim** [comment]
I see. But even as public, it is still in edit mode. Will it be possible to have a "play" mode where only the Remark slideshow is displayed?

**Comment by mikaelbr** [comment]
As in hide both the sidebar and the editor? Wouldn't it be just as easy to use the share-url? 

E.g.: http://www.markdowner.com/document/511b9fea4913db020000000e

**Comment by kerim** [comment]
OK. Sorry, I was looking for a "share" command and didn't realize that the URL at the top was such a thing. Now I know!

**Comment by mikaelbr** [comment]
Ah, I see I read your initial issue text wrong. Whereas I though you commented on that every Remark-document is public, you were talking about the opposite. 

But, yes. The URL on the top is the public URL. The button on the left toggles publicity (Hover to get a tool tip), and the button on the right toggles Remark-type. And as I said, per now remark-documents has to be public. But I'll implement a way around this.
